-- COUNT CONSULTATIONS
SELECT Consultation.ID_STAFF, COUNT(ID_CONSULTATION) AS ConsultationCount
FROM Consultation
GROUP BY ID_STAFF;

-- COUNT LECTURES
SELECT Lectures.STAFF_ID, Count(ID_Lectures) AS Lecture_Count
FROM Lectures
GROUP BY STAFF_ID;
-- VISUALIZE CONSULTATIONS
SELECT ID_CONSULTATION, CON_DATE, CON_TIME, PATIENT_ID, ID_STAFF, CON_PROBLEM
FROM Consultation;
-- VISUALIZE LECTURES
SELECT ID_LECTURES,LEC_DATE, LEC_TIME, TITLE, LEC_ROOM
FROM Lectures;
-- INNER JOIN STAFF-PATIENTS
SELECT Patients.*, STAFF.ST_NAME, ST_SURNAME, ST_GMAIL, ST_TYPE
FROM STAFF INNER JOIN Patients ON STAFF.ID_STAFF = Patients.ID_STAFF;
COMMIT;
-- LECTURES BILBOARD
SELECT ST_NAME, ST_SURNAME,  LEC_DATE, LEC_TIME, LEC_ROOM, TITLE
FROM Lectures INNER JOIN STAFF ON Lectures.STAFF_ID =STAFF.ID_STAFF;
COMMIT;
-- ORDER BY PROVENANCE
SELECT PA_ADDRESS, COUNT(PATIENT_ID) AS TotalCount
FROM Patients
GROUP BY PA_ADDRESS
ORDER BY COUNT(PATIENT_ID);
COMMIT;
-- GROUP BY TYPE
SELECT Patients.PA_TYPE, Count(Patients.PATIENT_ID) AS Count
FROM Patients
GROUP BY Patients.PA_TYPE
ORDER BY Count(Patients.PATIENT_ID);
COMMIT;
--UPDATE CONSULTATIONS
UPDATE Consultation
SET CON_DATE = TO_DATE('2024-02-03', 'YYYY-MM-DD'),
    CON_TIME = TO_TIMESTAMP('10:30:00', 'HH24:MI:SS')
WHERE ID_CONSULTATION = 1001;

--UPDATE LECTURES
UPDATE Lectures
SET LEC_DATE = TO_DATE('02/03/2024', 'MM/DD/YYYY'),
    LEC_TIME = TO_TIMESTAMP('16:30:00', 'HH24:MI:SS')
WHERE ID_LECTURES = '113B';

--DELETE CONSULTATIONS
DELETE FROM Consultation
WHERE ID_CONSULTATION = '1001';

--DELETE LECTURES
DELETE FROM Lectures 
WHERE ID_LECTURES = '112A';
COMMIT;

